version: "3.9"

services:
  db:
    image: postgres:12
    container_name: website_db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=websitedb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    depends_on:
      - server
    networks:
      - website

  server:
    build:
      context: ./server
    image: website-server
    container_name: website_server
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=websitedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - VIRTUAL_HOST=admin.rozhdestvo-youth.by
    volumes:
      - /app/node_modules
      - ./server:/app
    expose:
      - 1337
    networks:
      - website

  client:
    build:
      context: ./client
      network: host
    image: website-client
    container_name: website_client
    volumes:
      - /app/node_modules
      - ./client:/app
    expose:
      - 3000
    depends_on:
      - server
    networks:
      - website

  nginx:
    image: nginxproxy/nginx-proxy
    container_name: website_router
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/prod-nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - client
      - server
    networks:
      - website

volumes:
  db-data:
    name: website-db-data

networks:
  website:
    name: website-network
    driver: bridge
