name: Build server

on:
  push:
    branches:
      - master
    paths:
      - 'server/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Install packages"
        uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: cd /server && install
        
      - name: "Build app"
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: cd /server && build
