name: Build server

on:
  push:
    branches:
      - master
    paths:
      - 'server/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Install packages"
        uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: --cwd server install
        
      - name: "Build app"
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd server build

      - name: "Deploy to server"
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: cd platform && git pull