name: Deploy client

on:
  push:
    branches:
      - master
    paths:
      - 'client/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Deploy to server"
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: ${{ secrets.CLIENT_DEPLOYMENT_SCRIPT }}